product/urls.py
from django.urls import path
from .import views


app_name = "product"


urlpatterns =[
    path('homepage', views.homepage, name ="homepage"),
    path('', views.LoginView, name = "login"), 
    path('logout', views.logoutView, name = "logout"),
    path('details/<int:id>', views.productView, name ="detail"),
    path('filter-bike', views.filterBike, name="bike"),
    path('filter-clothes', views.filterClothes, name="cloth"),
    path('filter-book', views.filterBook, name="book"),
] 

suggest/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('product.urls', namespace="product")),
    
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

templates/bike.html
{% extends 'index.html' %}


{% block content %}
    <h3 class="text-center text-primary searchHead">
        Search Bikes
    </h3>
    <br><br><br>
    <div class="row">
        <div class="col-lg-8 col-12 m-auto">
        <form class="search-form p-3" method ="post">
            <div class="searchBox p-3 d-flex">
            <img src="https://freeiconshop.com/wp-content/uploads/edd/search-var-flat.png" alt="" >
            <input type="search" class="ms-2" id="search" name="search" placeholder="Search for bike">
            </div>
            <br>
            <div class="d-block">
            <button type="submit" class="btn btn-outline-primary p-2 pt-2">
                <h3>Search Now</h3>
            </button>
            </div>
        
        
        </form>
        </div>
        
    </div>

{% endblock content %}

templates/book.html
{% extends 'index.html' %}


{% block content %}
    <h3 class="text-center text-primary searchHead">
        Search Books
    </h3>
    <br><br><br>
    <div class="row">
        <div class="col-lg-8 col-12 m-auto">
            
        <form class="search-form p-3" method ="post">
            <div class="searchBox p-3 d-flex">
            <img src="https://freeiconshop.com/wp-content/uploads/edd/search-var-flat.png" alt="" >
            <input type="search" class="ms-2" id="search" name="search" placeholder="Search for books">
            </div>
            <br>
            <div class="d-block">
            <button type="submit" class="btn btn-outline-primary p-2 pt-2">
                <h3>Search Now</h3>
            </button>
            </div>
        
        
        </form>
        </div>
        
    </div>

{% endblock content %}

templates/cloth.html
{% extends 'index.html' %}


{% block content %}
    <h3 class="text-center text-primary searchHead">
        Search Clothes
    </h3>
    <br><br><br>
    <div class="row">
        <div class="col-lg-8 col-12 m-auto">
        <form class="search-form p-3" method ="post">
            <div class="searchBox p-3 d-flex">
            <img src="https://freeiconshop.com/wp-content/uploads/edd/search-var-flat.png" alt="" >
            <input type="search" class="ms-2" id="search" name="search" placeholder="Search for clothes">
            </div>
            <br>
            <div class="d-block">
            <button type="submit" class="btn btn-outline-primary p-2 pt-2">
                <h3>Search Now</h3>
            </button>
            </div>
        
        
        </form>
        </div>
        
    </div>

{% endblock content %}

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Recomend Management System</title>

    <style>
        .search-form {
           
            align-items: center;
            margin: 1rem 0;  /* Adjust margin as needed */
          }
          
          .search-form label {
            margin-right: 10px;
            font-weight: bold;
          }
          
          #search {
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 5px; /* Rounded corners for a modern look */
            font-size: 16px;
            width: 200px;  /* Adjust width as needed */
          }
          
          #search:focus {
            border-color: #66afe9;  /* Change border color on focus for better user feedback */
          }
          
          .search-form button {
            padding: 10px 15px;
            background-color: #3498db; /* Adjust button color to match your theme */
            color: white;
            border: none;
            border-radius: 5px;
            cursor: pointer;
          }
          
          .search-form button:hover {
            background-color: #2980b9; /* Darken button color slightly on hover */
          }
          
    </style>
    <link rel="stylesheet" href="{%static 'style'%}.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar bg-light">
        <div class="container-fluid d-flex">
          <h5 class="navbar-brand mb-0 h1">  Recomendation Management System</h5>
          
          {% if user.is_authenticated %}
          <a href="{%url 'product:logout'%}">
            <button class="btn btn-danger">Logout</button>
          </a>
          {% endif %}
            
          
        </div>

    </nav>
    <br><br>
    
    {% block content %}
    <h3 class="text-center text-primary searchHead">
      Search Any Motobike for different suggestion from flipkart
    </h3>
    <br><br><br>
    <div class="row">
      <div class="col-lg-8 col-12 m-auto">
        <form class="search-form p-3" method ="post">
          <div class="searchBox p-3 d-flex">
            <img src="https://freeiconshop.com/wp-content/uploads/edd/search-var-flat.png" alt="" >
            <input type="search" class="ms-2" id="search" name="search" placeholder="Search for cloths, bike or book">
          </div>
          <br>
          {% csrf_token %}
          <div class="d-block">
            <button class="btn btn-outline-primary p-2 pt-2" type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
              <h3>Search Now</h3>
            </button>
          </div>

          <!-- Modal -->
        <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h1 class="modal-title fs-5" id="staticBackdropLabel">Other Features</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body p-4">
                <p class="mt-2">Enter Price</p>
                <input type="text" class="form-control" name="price" id="">
                <p class="mt-2">Enter Milage</p>
                <input type="text" class="form-control" name="milage" id="">
                <p class="mt-2">Enter Power</p>
                <input type="text" class="form-control" name="power" id="">
              </div>
             
              <button  type="submit"  class="btn btn-danger">Search Now</button>
            </div>
          </div>
        </div>
         
         
       </form>
      </div>
      
     
     {% if data %}
      <img src="http://127.0.0.1:8000/media/piechart.png" alt="">
     {% endif %}
      
        
     
      {% if data %}
      <div class="col-12 p-3 m-auto">
        <h1 class="text-center">Your Result</h1>
        <p>{{data|safe}}</p>
      </div>
        
      {% endif %}
        
      
      
    </div>
    <!-- <div class="container">
      <img src="/Users/bibekdhakal/DJANGO/recomend/suggest/product/images/698_similarity_chart.png" alt="">
      <div class="row">
        <div class="col-lg-4 col-12 mt-3">
          <a href="{%url 'product:book'%}">
            <div class="card p-2 text-center">
              <img src="https://png.pngtree.com/png-clipart/20190617/original/pngtree-book-cartoon-books-simple-png-image_3881440.jpg" alt="">
              <small>Filter Only</small>
              <h5 class="text-info">Books</h5>
            </div>
          </a>

          
        </div>
  
        <div class="col-lg-4 col-12 mt-3">
          <a href="{%url 'product:cloth'%}">
            <div class="card p-2 text-center">
              <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ6b3OfFHWKkUnCXgPokuQRPiJkRI24EadVYJ5YiBYoRg&s" alt="">
              <small>Filter Only</small>
              <h5 class="text-info">Clothes</h5>
            </div>
          </a>
     
          
        </div>
  
        <div class="col-lg-4 col-12 mt-3">
          <a href="{%url 'product:bike'%}">
            <div class="card p-2 text-center">
              <img src="https://img.freepik.com/premium-psd/fast-motorcycle-transparent-background-3d-rendering-illustration_494250-30908.jpg" alt="">
              <small>Filter Only</small>
              <h5 class="text-info">Motorbike</h5>
            </div>
            
          </div>
          </a>
       
      </div>
    </div> -->
    {% endblock content %}
      
   


    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
</body>
</html>

templates/login.html
{% extends 'index.html' %}
{% load static %}

{% block content %}
   
<div class="login-box m-auto mt-5 p-0 ">
    
    {% for i in messages  %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <strong>Sorry</strong> {{i}}
       
      </div>
    {% endfor %}
        
                   
    <div class="row p-0 m-0">
        
        <div class="col-12 col-lg-6 my-auto m-auto  card mt-2 p-4 m-0 text-center">
            <img  src="{%static 'images/login.avif'%}" alt="" style="height: auto;width:50%">
          
            <h1 class="text-center mt-5">WELCOME</h1>
            <h4 class="text-center">Please Login to access the system</h4>
            
            <div class="text-center ">
                <!-- <img class="login-img" src="{%static 'images/loginlogo.jpeg'%}" alt="Gantabya EK"> -->
                <form method = "POST" class="mt-5">
                    <div class="d-flex mt-4 login-input position-relative">
                        <i class="fa fa-user-check my-auto icon"></i>
                        <input type="text" name="email_user" class=" form-control" placeholder="Your Email..">
                    </div>
                    <div class="d-flex mt-4 login-input position-relative">
                        <i class="fa fa-passport my-auto icon"></i> 
                        <input type="password" name = "password" class="form-control" placeholder="Password..">

                    </div>
                   
                    {% csrf_token %}
                    <div class="mt-3">
                        <button  type="submit" class="btn btn-primary mt-2 w-100">
                            Login
                        </button>
                    </div>
                   
                  
                    
                </form>
               
               
            </div>
        </div>
       
        
    </div>
</div>



{% endblock content %}

templates/productDetails.html
{% extends 'index.html' %}


{% block content %}
    <h3 class="text-center text-primary searchHead">
        {{id}}
    </h3>
    <br><br><br>
    <div class="row">
        <div class="col-lg-8 col-12 m-auto">
            <h3 class="text-center">
                Details {{id}}
            </h3>
            {{product|safe}}
        </div>
        
    </div>
     
    {% if data %}
    <div class="col-12 p-3 m-auto">
      <h1 class="text-center">You may also like using Collaborative Filtering</h1>
      <p>{{data|safe}}</p>
    </div>
      
    {% endif %}

{% endblock content %}